agents:
  PlannerAgent:
    prompt_file: "prompts/patched_prompts_v3/planner_prompt_sip_patched_v9.txt"
    model: "gemini"
    mcp_servers: []  # No tools needed
    
  RetrieverAgent:
    prompt_file: "prompts/patched_prompts_v3/retriever_prompt_sip_patched_v3.txt" 
    model: "gemini"
    mcp_servers: ["websearch"]
    # mcp_servers: ["documents", "websearch"]  # ✅ Fixed: Use actual server IDs
    
  ThinkerAgent:
    prompt_file: "prompts/patched_prompts_v3/thinker_prompt_sip_patched_v3.txt"
    model: "gemini"
    mcp_servers: []
    
  QAAgent:
    prompt_file: "prompts/patched_prompts_v3/qaagent_prompt_sip_patched_v3.txt"
    model: "gemini"
    mcp_servers: ["websearch"]  # ✅ Fixed: Use actual server ID

  DistillerAgent:
    prompt_file: "prompts/patched_prompts_v3/distiller_prompt_sip_patched_v3.txt"
    model: "gemini" 
    mcp_servers: []

  FormatterAgent:
    prompt_file: "prompts/patched_prompts_v3/formatter_prompt_sip_patched_v5.txt"
    model: "gemini"
    mcp_servers: []

  CoderAgent:
    prompt_file: "prompts/patched_prompts_v3/coder_prompt_sip_patched_v20.txt"
    model: "gemini"
    mcp_servers: ["websearch"]
    # mcp_servers: ["documents", "websearch"]  # ✅ Fixed: Give CoderAgent web tools

  ExecutorAgent:
    prompt_file: "prompts/executor_prompt.txt"
    model: "gemini"
    mcp_servers: []  # Executor uses different mechanism

  ClarificationAgent:
    prompt_file: "prompts/patched_prompts_v3/clarification_prompt_sip_patched_v3.txt"
    model: "gemini"
    mcp_servers: ["websearch"]  # ✅ May need web search for clarification

  SchedulerAgent:
    prompt_file: "prompts/patched_prompts_v3/scheduler_prompt_sip_patched_v3.txt"
    model: "gemini"
    mcp_servers: []

  SIPGoalPlannerAgent:
    prompt_file: "prompts/patched_prompts_v3/sip_goal_planner_prompt_patched_v2.txt"
    model: "gemini"
    mcp_servers: []  # No tools needed

  ReportGeneratorAgent:
    prompt_file: "prompts/patched_prompts_v3/report_prompt_sip_patched_v8.txt"
    model: "gemini"
    mcp_servers: []  # No tools needed
