agents:
  PlannerAgent:
    prompt_file: "prompts/planner_prompt_sip_patched_v12.txt"
    model: "gemini"
    mcp_servers: []  # No tools needed
    
  RetrieverAgent:
    prompt_file: "prompts/retriever_prompt_sip_patched_v8.txt" 
    model: "gemini"
    mcp_servers: ["websearch"]
    # mcp_servers: ["documents", "websearch"]  # ✅ Fixed: Use actual server IDs
    
  ThinkerAgent:
    prompt_file: "prompts/thinker_prompt_sip_patched_v5.txt"
    model: "gemini"
    mcp_servers: []
    
  QAAgent:
    prompt_file: "prompts/qaagent_prompt_sip_patched_v4.txt"
    model: "gemini"
    mcp_servers: ["websearch"]  # ✅ Fixed: Use actual server ID

  DistillerAgent:
    prompt_file: "prompts/distiller_prompt_sip_patched_v4.txt"
    model: "gemini" 
    mcp_servers: []

  FormatterAgent:
    prompt_file: "prompts/formatter_prompt_sip_patched_v9.txt"
    model: "gemini"
    mcp_servers: []

  CoderAgent:
    prompt_file: "prompts/coder_prompt_sip_patched_v32.txt"
    model: "gemini"
    mcp_servers: ["websearch"]
    # mcp_servers: ["documents", "websearch"]  # ✅ Fixed: Give CoderAgent web tools

  ExecutorAgent:
    prompt_file: "prompts/executor_prompt.txt"
    model: "gemini"
    mcp_servers: []  # Executor uses different mechanism

  ClarificationAgent:
    prompt_file: "prompts/clarification_prompt_sip_patched_v4.txt"
    model: "gemini"
    mcp_servers: ["websearch"]  # ✅ May need web search for clarification

  SchedulerAgent:
    prompt_file: "prompts/scheduler_prompt_sip_patched_v4.txt"
    model: "gemini"
    mcp_servers: []

  SIPGoalPlannerAgent:
    prompt_file: "prompts/sip_goal_planner_prompt_v4.txt"
    model: "gemini"
    mcp_servers: []  # No tools needed

  FundRecommendationAgent:
    prompt_file: "prompts/fund_recommendation_agent_prompt_v4.txt"
    model: "gemini"
    mcp_servers: []  # No tools needed

  ReportGeneratorAgent:
    prompt_file: "prompts/report_prompt_sip_patched_v15.txt"
    model: "gemini"
    mcp_servers: []  # No tools needed
